@echo off
echo Starting MongoDB...
echo Creating data directory if it doesn't exist...
if not exist C:\data\db mkdir C:\data\db

echo Starting MongoDB server...
start "MongoDB" mongod --dbpath=C:\data\db --bind_ip_all --port=27017

echo MongoDB is starting in a separate window...
echo You can close this window once MongoDB is running.
timeout /t 5
exit
